exclude: [rakefile]

markdown: rdiscount

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: soft
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false
